import io
import pandas as pd
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def generate_report(results, specs):
    total = len(results)
    passed = sum(1 for r in results if r['status'] == 'PASS')
    failed = sum(1 for r in results if r['status'] == 'FAIL')
    errors = sum(1 for r in results if r['status'] == 'ERROR')
    overall = "COMPLIANT" if failed == 0 else "NON-COMPLIANT"

    # ── Plain text report (kept for reference) ────────────────────────────────
    report_text = f"""BUILDING PLAN COMPLIANCE ASSESSMENT REPORT
==========================================
Generated by: D13 - KLE Technological University
Date: {datetime.now().strftime("%d %B %Y, %I:%M %p")}
Regulation: HDUDA Master Plan 2031

BUILDING DETAILS
----------------
Building Name  : {specs['building_name']}
Usage Type     : {specs['usage_type']}
Plot Area      : {specs['plot_area']} sq meters
Floors         : {specs['number_of_floors']}
Height         : {specs['building_height']} meters
FAR Proposed   : {specs['far_proposed']}
Ground Coverage: {specs['ground_coverage']}%
Front Setback  : {specs['front_setback']} m
Rear Setback   : {specs['rear_setback']} m
Side Setback   : {specs['side_setback']} m
Road Width     : {specs['road_width']} m

OVERALL STATUS: {overall}
==========================================

SUMMARY
-------
Total Checks : {total}
Passed       : {passed}
Failed       : {failed}
Errors       : {errors}

DETAILED COMPLIANCE RESULTS
----------------------------
"""
    for r in results:
        status_symbol = "PASS" if r['status'] == 'PASS' else "FAIL" if r['status'] == 'FAIL' else "ERROR"
        report_text += f"""
Parameter    : {r['parameter']}
Status       : {status_symbol}
Proposed     : {r['proposed_value']}
Allowed      : {r['regulation_limit']}
Citation     : {r['regulation_citation']}
Reason       : {r['reason']}
------------------------------------------"""

    if failed > 0:
        report_text += "\n\nNON-CONFORMITY REPORT\n=====================\n"
        for r in results:
            if r['status'] == 'FAIL':
                report_text += f"""
{r['parameter']}
Proposed Value     : {r['proposed_value']}
Regulation Limit   : {r['regulation_limit']}
Regulation Citation: {r['regulation_citation']}
Reason             : {r['reason']}
"""

    df = pd.DataFrame(results)
    return report_text, df


def generate_pdf_report(results, specs):
    """Generate a styled PDF compliance report and return as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm
    )

    total = len(results)
    passed = sum(1 for r in results if r['status'] == 'PASS')
    failed = sum(1 for r in results if r['status'] == 'FAIL')
    overall = "COMPLIANT" if failed == 0 else "NON-COMPLIANT"
    overall_color = colors.HexColor("#155724") if failed == 0 else colors.HexColor("#721c24")
    overall_bg = colors.HexColor("#d4edda") if failed == 0 else colors.HexColor("#f8d7da")

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=20, textColor=colors.white,
        alignment=TA_CENTER, spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#c5cae9"),
        alignment=TA_CENTER, spaceAfter=2
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"],
        fontSize=13, textColor=colors.HexColor("#1a237e"),
        spaceBefore=12, spaceAfter=6
    )
    normal_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=9, leading=13
    )
    small_style = ParagraphStyle(
        "Small", parent=styles["Normal"],
        fontSize=8, leading=11, textColor=colors.HexColor("#444444")
    )

    story = []

    # ── Header banner ─────────────────────────────────────────────────────────
    header_data = [[
        Paragraph("🏗️  Building Plan Compliance Checker", title_style),
    ]]
    header_table = Table(header_data, colWidths=[17.7 * cm])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1a237e")),
        ("ROUNDEDCORNERS", [8]),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 0.4 * cm))

    # Sub-header info
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %B %Y, %I:%M %p')}  |  "
        f"Regulation: HDUDA Master Plan 2031  |  KLE Technological University",
        ParagraphStyle("info", parent=styles["Normal"], fontSize=8,
                       textColor=colors.grey, alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 0.4 * cm))

    # ── Overall status banner ─────────────────────────────────────────────────
    status_data = [[Paragraph(
        f"OVERALL STATUS: {overall}",
        ParagraphStyle("status", parent=styles["Normal"], fontSize=16,
                       textColor=overall_color, alignment=TA_CENTER,
                       fontName="Helvetica-Bold")
    )]]
    status_table = Table(status_data, colWidths=[17.7 * cm])
    status_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), overall_bg),
        ("ROUNDEDCORNERS", [6]),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("BOX", (0, 0), (-1, -1), 1, overall_color),
    ]))
    story.append(status_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Summary metrics ───────────────────────────────────────────────────────
    summary_data = [
        [
            Paragraph(f"<b>{total}</b><br/>Total Checks",
                      ParagraphStyle("m", parent=styles["Normal"], fontSize=11, alignment=TA_CENTER)),
            Paragraph(f"<b>{passed}</b><br/>Passed",
                      ParagraphStyle("m", parent=styles["Normal"], fontSize=11, alignment=TA_CENTER,
                                     textColor=colors.HexColor("#155724"))),
            Paragraph(f"<b>{failed}</b><br/>Failed",
                      ParagraphStyle("m", parent=styles["Normal"], fontSize=11, alignment=TA_CENTER,
                                     textColor=colors.HexColor("#721c24"))),
        ]
    ]
    summary_table = Table(summary_data, colWidths=[5.9 * cm, 5.9 * cm, 5.9 * cm])
    summary_table.setStyle(TableStyle([
        ("BOX", (0, 0), (0, 0), 1, colors.HexColor("#aaaaaa")),
        ("BOX", (1, 0), (1, 0), 1, colors.HexColor("#28a745")),
        ("BOX", (2, 0), (2, 0), 1, colors.HexColor("#dc3545")),
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#f8f9fa")),
        ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#d4edda")),
        ("BACKGROUND", (2, 0), (2, 0), colors.HexColor("#f8d7da")),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("ROUNDEDCORNERS", [4]),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Building details ──────────────────────────────────────────────────────
    story.append(Paragraph("Building Details", section_style))
    details = [
        ["Building Name", specs['building_name'], "Usage Type", specs['usage_type']],
        ["Plot Area", f"{specs['plot_area']} sq m", "No. of Floors", str(specs['number_of_floors'])],
        ["Building Height", f"{specs['building_height']} m", "FAR Proposed", str(specs['far_proposed'])],
        ["Ground Coverage", f"{specs['ground_coverage']}%", "Road Width", f"{specs['road_width']} m"],
        ["Front Setback", f"{specs['front_setback']} m", "Rear Setback", f"{specs['rear_setback']} m"],
        ["Side Setback", f"{specs['side_setback']} m", "", ""],
    ]
    details_table = Table(details, colWidths=[4 * cm, 4.85 * cm, 4 * cm, 4.85 * cm])
    details_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eaf6")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#e8eaf6")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(details_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Compliance results table ───────────────────────────────────────────────
    story.append(Paragraph("Detailed Compliance Results", section_style))

    table_header = ["Parameter", "Proposed", "Allowed Limit", "Status", "Reason"]
    table_data = [table_header]
    for r in results:
        status_text = "✓ PASS" if r['status'] == 'PASS' else "✗ FAIL" if r['status'] == 'FAIL' else "⚠ ERROR"
        table_data.append([
            Paragraph(r['parameter'], small_style),
            Paragraph(str(r['proposed_value']), small_style),
            Paragraph(str(r['regulation_limit']), small_style),
            status_text,
            Paragraph(str(r['reason']), small_style),
        ])

    col_widths = [3.8 * cm, 2.2 * cm, 3.5 * cm, 1.8 * cm, 6.4 * cm]
    results_table = Table(table_data, colWidths=col_widths, repeatRows=1)

    row_styles = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    for i, r in enumerate(results, start=1):
        if r['status'] == 'PASS':
            row_styles.append(("BACKGROUND", (3, i), (3, i), colors.HexColor("#d4edda")))
            row_styles.append(("TEXTCOLOR", (3, i), (3, i), colors.HexColor("#155724")))
            row_styles.append(("FONTNAME", (3, i), (3, i), "Helvetica-Bold"))
        elif r['status'] == 'FAIL':
            row_styles.append(("BACKGROUND", (3, i), (3, i), colors.HexColor("#f8d7da")))
            row_styles.append(("TEXTCOLOR", (3, i), (3, i), colors.HexColor("#721c24")))
            row_styles.append(("FONTNAME", (3, i), (3, i), "Helvetica-Bold"))
        if i % 2 == 0:
            row_styles.append(("BACKGROUND", (0, i), (2, i), colors.HexColor("#f8f9fa")))
            row_styles.append(("BACKGROUND", (4, i), (4, i), colors.HexColor("#f8f9fa")))

    results_table.setStyle(TableStyle(row_styles))
    story.append(results_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Non-conformity section ────────────────────────────────────────────────
    failed_items = [r for r in results if r['status'] == 'FAIL']
    if failed_items:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dc3545")))
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph("Non-Conformity Report", ParagraphStyle(
            "nc", parent=styles["Heading2"], fontSize=13,
            textColor=colors.HexColor("#721c24"), spaceBefore=6, spaceAfter=6
        )))

        for r in failed_items:
            nc_data = [
                [Paragraph(f"❌  {r['parameter']}", ParagraphStyle(
                    "nch", parent=styles["Normal"], fontSize=10,
                    fontName="Helvetica-Bold", textColor=colors.HexColor("#721c24")
                ))],
                [Table([
                    ["Proposed Value", str(r['proposed_value'])],
                    ["Regulation Limit", str(r['regulation_limit'])],
                    ["Regulation Citation", str(r['regulation_citation'])],
                    ["Reason", str(r['reason'])],
                ], colWidths=[4 * cm, 12.7 * cm],
                    style=TableStyle([
                        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#fff3f3")),
                        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#f5c6cb")),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ])
                )]
            ]
            nc_outer = Table(nc_data, colWidths=[17.7 * cm])
            nc_outer.setStyle(TableStyle([
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#f5c6cb")),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8d7da")),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("ROUNDEDCORNERS", [4]),
            ]))
            story.append(nc_outer)
            story.append(Spacer(1, 0.3 * cm))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        "Generated by Building Plan Compliance Checker | D13 - KLE Technological University | HDUDA Master Plan 2031",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=7,
                       textColor=colors.grey, alignment=TA_CENTER, spaceBefore=4)
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
